name: Setup Python Project Environment
description: |
  Sets up the Python project environment for code quality checks and builds.

runs:
  using: composite
  steps:
    - name: Install uv package manager
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python runtime
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Install dependencies
      run: uv sync --all-groups
      shell: bash
