name: Release

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv package manager
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true

      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Ruff linter
        run: uv run ruff check

      - name: Check code formatting
        run: uv run ruff format --check


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv package manager
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Create release
        run: uv run semantic-release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
